version: '3.8'

services:
  backend:
    build: ./scrum-backend
    image: akasbiacrpfa.azurecr.io/scrum-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://hamza:hamza@mongo:27017/scrumdb?authSource=admin
    depends_on:
      - mongo
    networks:
      - scrum

  frontend:
    build: ./scrum-frontend
    image: akasbiacrpfa.azurecr.io/scrum-frontend:latest
    ports:
      - "3000:80"
    networks:
      - scrum

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Utilisation d'un volume nommé pour /data/db
      - C:/Users/PC/Desktop/export:/data/db  # Montrez votre répertoire local sur /data/db dans le conteneur
    environment:
      MONGO_INITDB_ROOT_USERNAME: hamza
      MONGO_INITDB_ROOT_PASSWORD: hamza
      MONGO_INITDB_DATABASE: scrumdb
    networks:
      - scrum

volumes:
  mongo-data:

networks:
  scrum:
    driver: bridge
