version: '3.8'

services:
  backend:
    build: ./scrum-backend
    image: scrumifyacr.azurecr.io/scrum-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://hamza:hamza@scrum-mongo-service:27017/scrumdb?authSource=admin
    depends_on:
      - scrum-mongo-service
    networks:
      - scrum

  frontend:
    build: ./scrum-frontend
    image: scrumifyacr.azurecr.io/scrum-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - scrum

  scrum-mongo-service:
    build: ./database  
    image: scrumifyacr.azurecr.io/scrum-mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: hamza
      MONGO_INITDB_ROOT_PASSWORD: hamza
      MONGO_INITDB_DATABASE: scrumdb
    networks:
      - scrum

volumes:
  mongo-data:

networks:
  scrum:
    driver: bridge