# Dockerfile for Spring Boot application

# Utiliser une image de base compatible Java
FROM openjdk:11-jre-slim

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copier le jar compilé dans le conteneur
COPY target/scrum-backend-0.0.1-SNAPSHOT.jar app.jar

# Commande à exécuter à l'intérieur du conteneur pour démarrer l'application
CMD ["java", "-jar", "app.jar"]
