apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrum-mongo-deployment
  labels:
    app: scrum-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrum-mongo
  template:
    metadata:
      labels:
        app: scrum-mongo
    spec:
      imagePullSecrets:
      - name: scrum-secret
      containers:
      - name: scrum-mongo
        image: scrumifyacr.azurecr.io/scrum-mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "hamza"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "hamza"
        - name: MONGO_INITDB_DATABASE
          value: "scrumdb"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: scrum-mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrum-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: scrum-mongo-service
spec:
  selector:
    app: scrum-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP